language: ruby
rvm:
- 2.2.1
deploy:
  provider: rubygems
  api_key:
    secure: MFKQmuIxmBH49OpDUPjcoDKdjsgNlOLQu8v0wST4aezUAGH6U09+dKgb8e78rBeItAvnjbIecW0SzreHTtUkdEZISFlPWjuzKtmeJ5OalCxHD3HEKpLGQFI3EJUOAD+bu/4u1GX7OcA3I4iqcRUMiRbkKlVNQjV0QkQxlZQv+AQjKbhUXYJ7GxGps17axH8r0QfUy6oOn0vY+SXiZKnutoyQoHN3JWYVHjy+1Uy6A05RkWgc4ZQEt8PcCix0SrEuibD52sVU+lJ/QBr+j0yeEVk12lUNrMZIeIiIBhJdu4qkxJFmMqWpNZHcMkU0EwrjroqXUbOVOnfyJH1PQ/1Ga/SLsHrc3A+zCESjBdzqTbfh4Kg7Z/nIiTw/UAe6mO1scd2JWPCrTE/i4ZR9sfJLV4Wi/P5/kllYVTgqCDYy9Obgyxv+vhDHPsNa6hMbDW3W3lWe660zmVMYv+zB9vzh3sYleA5Kx2iICJzy04krdhLXD2YErQzGiR+F5f6H6ZtZyX9B28Ab3Af4vvLqNYwtGE1BH+5nP4undXGmDnH5PkNj0UHeNb4KADJncNGhk3DtSuOxBhg52y6i/s1T4qW0+WaXJjGqOZhpEXyMyh+M5rUnFZ5MmdOLeFPqzw8rhzl7IgR5cFVbwfpAHYMp64QBkjWiNI/QiXtIcX9iGJbVcRs=
  gem: path_mapper
  on:
    tags: true
    repo: flant/path_mapper
